version: '3'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    env_file:
      - ./DB/.env
    volumes:
      - ./DB/data:/var/lib/mysql
    networks:
      - economy-bot
  bot:
    build: dongsu8142/economy-bot
    env_file:
      - .env
      - ./DB/.env
    depends_on:
      - db
    networks:
      - economy-bot

networks:
  economy-bot:
    driver: bridge