name: Docker CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@latest
        with:
          image: dongsu8142/economy-bot@v2.9.0
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: dongsu8142/economy-bot
          tags: latest, ${{ github.run_number }}
